### ISSUE TITLE
v0.0.1 Progress Tracker

### ISSUE THREAD

**Issue by mia1024** [mia1024/restructured-notes#1]
- v 0.0.1
	- Logic
		- [ ] OOP model for notebook fs representation
		- [ ] Git/VCS integration
		- [ ] database for tags (MongoDB)
		- [ ] multi-instance editor lock
	- UI
		- VCS
			- [ ] notebook/note creation dialog
			- [ ] on save summary (commit message) dialog
			- [ ] version revert page
		- Settings
			- [ ] global settings page
			- [ ] per notebook settings page
		- Navigation
			- [ ] URL scheme registration 
			- [ ] plain text editor for notes
			- [ ] Directory/notebook tree viewer
		- [x] Launcher icon (e37cd84)
		- [ ] Dialog for detection warning
		- [ ] i18n
	- Docs
		- [ ] fs model for a notebook
		- [ ] tag DB architectures
		- [ ] URL scheme
	- Unittest 
		- [ ] fs operations
		- [ ] tags 
		- [ ] UI navigation
		- [ ] settings
		- [ ] URL scheme
